version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: my_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://user:password@postgres:5432/mydb?schema=public"
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma db seed &&
             npm run start"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  postgres_data:
